"""add into Post model body_html converted from Markdwon text

Revision ID: 59ae69373c45
Revises: 8be2b29c165c
Create Date: 2018-01-27 16:54:54.820699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ae69373c45'
down_revision = '8be2b29c165c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
